taskManager/taskManager/urls.py
from django.contrib import admin
from django.urls import path, re_path
from tasks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('add_task', views.new),
    path('show_tasks', views.show_tasks),
    path('edit_task/<int:id>', views.edit_task),
    path('update_task/<int:id>', views.update_task),
    path('delete_task/<int:id>', views.kill_task),
    path('status/<int:id>', views.status),
    path('timestamp/<int:id>', views.timestamp),
    path('show_timestamps', views.show_timestamps),
    path('timestamp_search', views.timestamp_search),
    path('delete_timestamp/<int:id>', views.delete_timestamp),
    path('edit_timestamp/<int:id>', views.edit_timestamp),
    path('update_timestamp/<int:id>', views.update_timestamp),
	  path('show_time_dashboard', views.show_time_dashboard),
    path('show_task_dashboard', views.show_task_dashboard),
	  re_path(r'^$', views.index, name='index'),
]

taskManager/tasks/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.index, name='index'),
]

taskManager/tasks/models.py
from django.db import models
import math

# Create your models here.
STATUSES = (
    ('in progress', 'In Progress'),
    ('completed', 'Complete'),
)

TIMER_STATE = (
    ('Start Timer', 'start timer'),
    ('Stop Timer', 'stop timer'),
)

class Timestamp(models.Model):
    task = models.ForeignKey('Task', on_delete=models.CASCADE, null=True)
    begin_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField()

    def elapsed_time(self):
        return math.floor(((self.end_time - self.begin_time).total_seconds()/60))
    class Meta:
        db_table = "timestamps"

class Task(models.Model):
    task_name = models.CharField(max_length=100)
    task_description = models.TextField()
    timer_state = models.CharField(max_length=11, choices=TIMER_STATE, default='Start Timer') #Used to determine if the task should be tracking time to create a timestamp
    begin_time = models.DateTimeField(blank=True, null=True) #Needed to record start time of timestamps.
    project = models.CharField(max_length=100)
    status = models.CharField(max_length=11, choices=STATUSES, default='in progress')
    class Meta:
        db_table = "tasks"

taskManager/tasks/forms.py
from django import forms
from tasks.models import Task, Timestamp

#Override dateinput and datetimeinput so that django can read the html date and datetime selectors
class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'

class DateInput(forms.DateInput):
    input_type = 'date'

#Add new task
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["task_name", "task_description", "project", "status"]

class UpdateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["task_name", "task_description", "project"]

class StatusForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["status"]

#Task filter on list of timestamps
class TimestampSearchForm(forms.Form):
    task_name = forms.CharField(label="id_task_name", max_length=100)

#Update Timestamp Form
class UpdateTsForm(forms.ModelForm):
    class Meta:
        model = Timestamp
        fields = ["begin_time", "end_time"]
        widgets = {'begin_time' : DateTimeInput(), 'end_time' : DateTimeInput()}

#For week / month selector on dashboards
class DateFilter(forms.Form):
    day = forms.DateField(label="date_filter", widget=DateInput())

taskManager/tasks/views.py
from django.shortcuts import render, redirect
from tasks.forms import TaskForm, UpdateTaskForm, StatusForm, TimestampSearchForm, UpdateTsForm, DateFilter
from tasks.models import Task, Timestamp
from django.utils import timezone
from collections import defaultdict
from django.db.models import Sum
from datetime import timedelta, date, datetime
import pytz
import math

# Create your views here.
#When you access the main page (127.0.0.1/8000/) automatically redirect to show_tasks page
def index(request):
	return redirect("/show_tasks")

#add task page
def new(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show_tasks')
            except:
                pass
    else:
        form = TaskForm()
    return render(request,'add_task.html',{'form':form})


def show_tasks(request):
    tasks = Task.objects.all()
    return render(request, "show_tasks.html", {'tasks':tasks})

#show edit task page
def edit_task(request, id):
    tasks = Task.objects.get(id=id)
    form = UpdateTaskForm(initial={'task_name':tasks.task_name, 'task_description':tasks.task_description, 'project':tasks.project})
    return render(request, "edit_task.html", {'tasks':tasks, 'form':form})

#take edit task input and actually update the database
def update_task(request, id):
    tasks = Task.objects.get(id=id)
    if request.method == "POST":
        form = UpdateTaskForm(request.POST, instance=tasks)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show_tasks')
            except:
                pass
    else:
        form = UpdateTaskForm(initial={'task_name':tasks.task_name, 'task_description':tasks.task_description, 'project':tasks.project})
    return render(request, "edit_task.html", {'tasks':tasks, 'form':form})

#delete task
def kill_task(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect("/show_tasks")

#update tasks status
def status(request, id):
    tasks = Task.objects.get(id=id)
    form = StatusForm(request.POST, instance=tasks)
    form.save()
    return redirect("/show_tasks")

#Create new timestamp for a task
def timestamp(request, id):
    task = Task.objects.get(id=id)
    #If timer state is 'start timer' the task does not have an active timestamp so set begin_time and flip timer state
    if(task.timer_state == 'Start Timer'):
        task.begin_time = timezone.now()
        task.timer_state = "Stop Timer"
        task.save()
    #If timer state is 'stop timer', a timestamp has already been started so create a new timestamp object and flip timer state
    else:
        new_ts = Timestamp(task=task, begin_time=task.begin_time, end_time=timezone.now())
        task.timer_state = "Start Timer"
        task.save()
        new_ts.save()
    return redirect("/show_tasks")

#Task filter on list of timestamps
def timestamp_search(request):
    form = TimestampSearchForm(request.POST)
    if form.is_valid():
        timestamps = Timestamp.objects.filter(task__task_name=form.cleaned_data['task_name']).order_by('begin_time')
        return render(request, "show_timestamps.html", {'timestamps':timestamps})
    return redirect("/show_timestamps")

def show_timestamps(request):
    timestamps = Timestamp.objects.all().order_by('begin_time')
    return render(request, "show_timestamps.html", {'timestamps':timestamps})

def delete_timestamp(request, id):
    ts = Timestamp.objects.get(id=id)
    # Attempts to retain a search. If the request came from show_timestamps it came from the full list of timestamps so return the full list
    if "show_timestamps" in request.META['HTTP_REFERER']:
        ts.delete()
        return redirect("/show_timestamps")
    # otherwise, redo the search for a task and return the filtered list
    else:
        ts.delete()
        timestamps = Timestamp.objects.filter(task__task_name=ts.task.task_name).order_by('begin_time')
        return render(request, "show_timestamps.html", {'timestamps':timestamps})

#same process as edit_task
def edit_timestamp(request, id):
    timestamp=Timestamp.objects.get(id=id)
    form = UpdateTsForm()
    return render(request, 'edit_timestamp.html', {'timestamp':timestamp, 'form':form})

#Because edit, update is a 2 step process, cannot use the HTTP_REFERER trick to retain a search, so edit will always return the full list of timestamps
def update_timestamp(request, id):
    timestamp = Timestamp.objects.get(id=id)
    if request.method == 'POST':
        form = UpdateTsForm(request.POST, instance=timestamp)
        if form.is_valid() and form.cleaned_data['begin_time'] < form.cleaned_data['end_time']:
            try:
                form.save()
                return redirect("/show_timestamps")
            except:
                pass
    form = UpdateTsForm()
    return render(request, "edit_timestamp.html", {'form':form, 'timestamp':timestamp})

def show_time_dashboard(request):
    tasks = Task.objects.all()
    ts_total = {}
    ts_week = {}
    ts_month = {}
    if request.method == 'POST':
        #If a date is specified, extract the year, month, and the start of the week
        date_form = DateFilter(request.POST)
        if date_form.is_valid():
            year = date_form.cleaned_data['day'].year
            month = date_form.cleaned_data['day'].month
            week_start = date_form.cleaned_data['day'] - timedelta(days=date_form.cleaned_data['day'].weekday())
    #Otherwise use todays date
    else:
        date_form = DateFilter()
        year = date.today().year
        month = date.today().month
        week_start = date.today() - timedelta(days=date.today().weekday())
    week_end = week_start + timedelta(days=6)
    #Calculate the week and month start and end as a localized datetime. This makes calculations with the timestamp values easier as everything is the same type
    #Also fixes a bug where because datetimes are always stored in the database as UTC times, datetime.day would be off by 1 if the datetime is late at night or early in the morning because of time change
    week_start_time = pytz.timezone('US/Eastern').localize(datetime.combine(week_start, datetime.min.time()))
    week_end_time = pytz.timezone('US/Eastern').localize(datetime.combine(week_end, datetime.max.time()))
    month_start_time = pytz.timezone('US/Eastern').localize(datetime(year, month, 1, 0, 0))
    month_end_time = pytz.timezone('US/Eastern').localize(datetime((year+1 if month==12 else year), (1 if month==12 else month+1), 1, 0, 0))
    #Looks for projects for the filter by projects later
    projects = set()
    for task in tasks:
        timestamps = Timestamp.objects.filter(task__id=task.id)
        projects.add(task.project)
        #Total time for each task
        ts_total[task.id] = 0
        #Time spent on the task this week
        ts_week[task.id] = 0
        #Time spent on the task this month
        ts_month[task.id] = 0
        for timestamp in timestamps:
            ts_total[task.id] += timestamp.elapsed_time()
            #If the timestamp begins and ends withing the week, whole timestamp is added to weekly time
            if timestamp.begin_time >= week_start_time and timestamp.end_time <= week_end_time:
                ts_week[task.id] += timestamp.elapsed_time()
            #If timestamps starts before the week but ends within the week, only the time between the start of the week and the end of the timestamp is added
            if timestamp.begin_time < week_start_time and timestamp.end_time <= week_end_time and timestamp.end_time > week_start_time:
                ts_week[task.id] += math.floor((timestamp.end_time - week_start_time).total_seconds()/60)
            #If the timestamp starts during the week but ends after the week, only the time from the start of the timestamp to the end of the week is added
            if timestamp.begin_time <= week_end_time and timestamp.begin_time >= week_start_time and timestamp.end_time > week_end_time:
                ts_week[task.id] += math.floor((week_end_time - timestamp.begin_time).total_seconds()/60) + 1 #Need +1 because week_end_time is at 11:59 pm, need to add last minute
            #If the timestamp starts before the week and ends after the week, the whole week is added
            if timestamp.begin_time < week_start_time and timestamp.end_time > week_end_time:
                ts_week[task.id] += math.floor((week_end_time - week_start_time).total_seconds()/60) + 1
            #Same logic for month as for week
            if timestamp.begin_time >= month_start_time and timestamp.end_time <= month_end_time:
                ts_month[task.id] += timestamp.elapsed_time()
            if timestamp.begin_time < month_start_time and timestamp.end_time <= month_end_time and timestamp.end_time > month_start_time:
                ts_month[task.id] += math.floor((timestamp.end_time - month_start_time).total_seconds()/60)
            if timestamp.begin_time >= month_start_time and timestamp.end_time > month_end_time and timestamp.begin_time < month_end_time:
                ts_month[task.id] += math.floor((month_end_time - timestamp.begin_time).total_seconds()/60)
            if timestamp.begin_time < month_start_time and timestamp.end_time > month_end_time:
                ts_month[task.id] += math.floor((month_end_time - month_start_time).total_seconds()/60)

    p_total = {}
    p_week = {}
    p_month = {}
    #Does the exact same process as for tasks but loops through the different projects
    for project in projects:
        timestamps = Timestamp.objects.filter(task__project=project)
        p_total[project] = 0
        p_week[project] = 0
        p_month[project] = 0
        for timestamp in timestamps:
            p_total[project] += timestamp.elapsed_time()
            if timestamp.begin_time >= week_start_time and timestamp.end_time <= week_end_time:

taskManager/tasks/templates/add_task.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Add Task</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<style>

		html *{
    		font-family: "Gill Sans", sans-serif !important;
		}

		header {
          background: #487;
        }

        header::after {
          content: '';
          display: table;
          clear: both;
        }

        .logo {
          float: left;
          padding-top: 15px;
		  margin-left: 10px;
		  padding-bottom: 10px;
          border: none;
        }

        nav {
          float: right;
        }

        nav ul {
          margin: 0;
          padding: 0;
          list-style: none;
        }

        nav li {
		  color: #ffffff;
          display: inline-block;
          margin-left: 20px;
		  margin-right: 20px;
		  padding-top: 20px;
          position: relative;
        }

        nav a {
          color: #ffffff;
        }

        nav a:hover {
          color: #e5ff00;
        }

        nav a::before {
          content: '';
          display: block;
          height: 5px;
          background-color: #487;

          position: absolute;
          top: 0;
          width: 0%;

          transition: all ease-in-out 250ms;
        }

        nav a:hover::before {
          width: 100%;
        }

		h3 {
			color: #f8f9fa;
		}

        form {
    		display: inline;
		}

	</style>
</head>
<body>
	<header>
		<div class="container_h">
			<h3 class="logo"><b>Add Task</b></h3>

			<nav>
				<ul>
					<li><a href="/show_tasks">Tasks List</a></li>
					<li><a href="/show_timestamps">Timestamps</a></li>
					<li><a href="/show_task_dashboard">Task Dashboard</a></li>
					<li><a href="/show_time_dashboard">Time Dashboard</a></li>
				</ul>
			</nav>

		</div>
	</header>
<div style="padding-left: 10px;">
<form method="POST" action="/add_task">
    {% csrf_token %}
<br>
    <h3 style="color: black;">Enter Details</h3>
    <label>Task Name:</label>
		{{ form.task_name }}
	<br>

    <label>Task Description:</label>
	<br>
		{{ form.task_description }}
	<br>

    <label>Project:</label>
		{{ form.project }}
	<br>

    <label>Status:</label>
		{{ form.status }}
	<br>

    <button type="submit">Submit</button>
</form>
<form method="POST" action="/show_tasks">
    {% csrf_token %}
    <button type="submit">Cancel</button>
</form>
</div>
</body>
</html>

taskManager/tasks/templates/edit_task.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Edit Task</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<style>

		html *{
    		font-family: "Gill Sans", sans-serif !important;
		}

		header {
          background: #487;
        }

        header::after {
          content: '';
          display: table;
          clear: both;
        }

        .logo {
          float: left;
          padding-top: 15px;
		  margin-left: 10px;
		  padding-bottom: 10px;
          border: none;
        }

        nav {
          float: right;
        }

        nav ul {
          margin: 0;
          padding: 0;
          list-style: none;
        }

        nav li {
		  color: #ffffff;
          display: inline-block;
          margin-left: 20px;
		  margin-right: 20px;
		  padding-top: 20px;
          position: relative;
        }

        nav a {
          color: #ffffff;
        }

        nav a:hover {
          color: #e5ff00;
        }

        nav a::before {
          content: '';
          display: block;
          height: 5px;
          background-color: #487;

          position: absolute;
          top: 0;
          width: 0%;

          transition: all ease-in-out 250ms;
        }

        nav a:hover::before {
          width: 100%;
        }

		h3 {
			color: #f8f9fa;
		}

	</style>
</head>
<body>
	<header>
		<div class="container_h">
			<h3 class="logo"><b>Edit Task</b></h3>

			<nav>
				<ul>
					<li><a href="/show_tasks">Tasks List</a></li>
					<li><a href="/show_timestamps">Timestamps</a></li>
					<li><a href="/show_task_dashboard">Task Dashboard</a></li>
					<li><a href="/show_time_dashboard">Time Dashboard</a></li>
				</ul>
			</nav>

		</div>
	</header>

<div style="padding-left: 10px;">
<form method="POST" action="/update_task/{{tasks.id}}">
	<div class="form-group">
	<thead class="thead-dark">
	{% csrf_token %}
<br>
    <label>Task Name:</label>
		{{ form.task_name }}
	<br>

    <label>Task Description:</label>
	<br>
        {{ form.task_description }}
	<br>
    <label>Project:</label>
        {{form.project }}
	<br>

    <button type="submit">Update</button>
	</div>
</form>
</div>
</body>
</html>

taskManager/tasks/templates/edit_timestamp.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Edit TS</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<style>

		html *{
    		font-family: "Gill Sans", sans-serif !important;
		}

		header {
          background: #487;
        }

        header::after {
          content: '';
          display: table;
          clear: both;
        }

        .logo {
          float: left;
          padding-top: 15px;
		  margin-left: 10px;
		  padding-bottom: 10px;
          border: none;
        }

        nav {
          float: right;
        }

        nav ul {
          margin: 0;
          padding: 0;
          list-style: none;
        }

        nav li {
		  color: #ffffff;
          display: inline-block;
          margin-left: 20px;
		  margin-right: 20px;
		  padding-top: 20px;
          position: relative;
        }

        nav a {
          color: #ffffff;
        }

        nav a:hover {
          color: #e5ff00;
        }

        nav a::before {
          content: '';
          display: block;
          height: 5px;
          background-color: #487;

          position: absolute;
          top: 0;
          width: 0%;

          transition: all ease-in-out 250ms;
        }

        nav a:hover::before {
          width: 100%;
        }

		h3 {
			color: #f8f9fa;
		}

		form {
    		display: inline;
		}

	</style>

</head>


	<body>
		<header>
			<div class="container_h">
				<h3 class="logo"><b>Edit Timestamps</b></h3>

				<nav>
					<ul>
						<li><a href="/show_tasks">Tasks List</a></li>
						<li><a href="/show_timestamps">Timestamps</a></li>
						<li><a href="/show_task_dashboard">Task Dashboard</a></li>
						<li><a href="/show_time_dashboard">Time Dashboard</a></li>
					</ul>
				</nav>


			</div>
		</header>

		<div style="padding-left: 10px;">
			<form method="POST" action="/update_timestamp/{{timestamp.id}}">
				{% csrf_token %}
				<br>
				<label>Begin Time:</label>
					{{ form.begin_time }}
				<br>
				<br>

				<label>End Time:</label>
					{{ form.end_time }}
				<br>
				<br>
				<button type="submit">Update</button>
			</form>

			<form method="POST" action="/show_timestamps">
				{% csrf_token %}
				<button type="submit">Cancel</button>
			</form>
		</div>
	</body>
</html>

taskManager/tasks/templates/index.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Add Task</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<style>

		html *{
    		font-family: "Gill Sans", sans-serif !important;
		}

		header {
          background: #487;
        }

        header::after {
          content: '';
          display: table;
          clear: both;
        }

        .logo {
          float: left;
          padding-top: 15px;
		  margin-left: 10px;
		  padding-bottom: 10px;
          border: none;
        }

        nav {
          float: right;
        }

        nav ul {
          margin: 0;
          padding: 0;
          list-style: none;
        }

        nav li {
		  color: #ffffff;
          display: inline-block;
          margin-left: 20px;
		  margin-right: 20px;
		  padding-top: 20px;
          position: relative;
        }

        nav a {
          color: #ffffff;
        }

        nav a:hover {
          color: #e5ff00;
        }

        nav a::before {
          content: '';
          display: block;
          height: 5px;
          background-color: #487;

          position: absolute;
          top: 0;
          width: 0%;

          transition: all ease-in-out 250ms;
        }

        nav a:hover::before {
          width: 100%;
        }

		h3 {
			color: #f8f9fa;
		}

        form {
    		display: inline;
		}

	</style>
</head>
<body>
	<header>
		<div class="container_h">
			<h3 class="logo"><b>Add Task</b></h3>
			<nav>
				<ul>
					<li><a href="/show_tasks">Tasks List</a></li>
					<li><a href="/show_timestamps">Timestamps</a></li>
					<li>Tasks Dashboard</li>
					<li>Timer Dashboard</li>
				</ul>
			</nav>
		</div>
	</header>
<div style="padding-left: 10px;">
<form method="POST" action="/new">
    {% csrf_token %}
<br>
    <h3 style="color: black;">Enter Details</h3>
    <label>Task Name:</label>
		{{ form.task_name }}
	<br>

    <label>Task Description:</label>
	<br>
		{{ form.task_description }}
	<br>

    <label>Project:</label>
		{{ form.project }}
	<br>

    <label>Status:</label>
		{{ form.status }}
	<br>

    <button type="submit">Submit</button>
</form>
<form method="POST" action="/show_tasks">
    {% csrf_token %}
    <button type="submit">Cancel</button>
</form>
</div>
</body>
</html>

taskManager/tasks/templates/show_tasks.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Task Manager</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<style>

		html *{
    		font-family: "Gill Sans", sans-serif !important;
		}

		header {
          background: #487;
        }

        header::after {
          content: '';
          display: table;
          clear: both;
        }

        .logo {
          float: left;
          padding-top: 15px;
		  margin-left: 10px;
		  padding-bottom: 10px;
          border: none;
        }

        nav {
          float: right;
        }

        nav ul {
          margin: 0;
          padding: 0;
          list-style: none;
        }

        nav li {
		  color: #ffffff;
          display: inline-block;
          margin-left: 20px;
		  margin-right: 20px;
		  padding-top: 20px;
          position: relative;
        }

        nav a {
          color: #ffffff;
        }

        nav a:hover {
          color: #e5ff00;
        }

        nav a::before {
          content: '';
          display: block;
          height: 5px;
          background-color: #487;

          position: absolute;
          top: 0;
          width: 0%;

          transition: all ease-in-out 250ms;
        }

        nav a:hover::before {
          width: 100%;
        }

		h3 {
			color: #f8f9fa;
		}

	</style>


</head>


<body>

<header>
	<div class="container_h">
		<h3 class="logo"><b>List of tasks</b></h3>
		<nav>
			<ul>
				<li><a href="/show_tasks">Tasks List</a></li>
				<li><a href="/show_timestamps">Timestamps</a></li>
				<li><a href="/show_task_dashboard">Task Dashboard</a></li>
				<li><a href="/show_time_dashboard">Time Dashboard</a></li>
			</ul>
		</nav>
	</div>
</header>

<br>
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Task Name</th>
        <th>Task Description</th>
		<th>Project</th>
        <th>Timestamp</th>
        <th>Status</th>
		<th>Change Status</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for task in tasks %}
    <tr>
        <td>{{ task.task_name }}</td>
        <td>{{ task.task_description }}</td>
        <td>{{ task.project }}</td>
		<td>
			<form method="POST" action="/timestamp/{{task.id}}">
				{% csrf_token %}
				<button type="submit">{{ task.timer_state }}</button>
			</form>
		</td>
        <td>{{ task.status }}</td>
		<td>
			<form method="POST" action="/status/{{task.id}}">
				{% csrf_token %}
				<select id="id_status" name="status">
					<option value="in progress">In Progress</option>
					<option value="completed">Completed</option>
				</select>
				<button type="submit">Update Status</button>
			</form>
		</td>
        <td>
            <a href="/edit_task/{{ task.id }}">Edit</a>
			<b> | </b>
            <a href="/delete_task/{{ task.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/add_task">Add New Task</a></center>

</body>
</html>